-- vim.pack.add { 'https://github.com/folke/noice.nvim' }
--
-- require('noice').setup {
--   -- -- you can enable a preset for easier configuration
--   presets = {
--     --   bottom_search = true, -- use a classic bottom cmdline for search
--     --   command_palette = true, -- position the cmdline and popupmenu together
--     --   long_message_to_split = true, -- long messages will be sent to a split
--     --   inc_rename = false, -- enables an input dialog for inc-rename.nvim
--     lsp_doc_border = true, -- add a border to hover docs and signature help
--   },
--   cmdline = {
--     enabled = true,
--     view = 'cmdline',
--   },
--   lsp = {
--     -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
--     override = {
--       ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
--       ['vim.lsp.util.stylize_markdown'] = true,
--       -- ['cmp.entry.get_documentation'] = true, -- requires hrsh7th/nvim-cmp
--     },
--     signature = {
--       enabled = false,
--     },
--     hover = {
--       enabled = false,
--     },
--   },
-- }
--
-- vim.keymap.set('n', '<leader>nh', '<cmd>Noice history<cr>', { desc = 'History' })
-- vim.keymap.set('n', '<leader>nf', '<cmd>Noice fzf<cr>', { desc = 'Find(Fzf)' })
-- vim.keymap.set('n', '<leader>nd', '<cmd>Noice dismiss<cr>', { desc = 'Dismiss' })
-- vim.keymap.set('n', '<leader>.', '<cmd>Noice dismiss<cr>', { desc = 'Noice Dismiss' })
